### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by mattl** [no-reply/rights-app-prototype#2]
Can we put a free software license on this?

**Comment by no-reply** [comment]
I understand us to be waiting on the resolution of a licensing discussion for the project. I would advocate [Unlicense](http://unlicense.org/), but I believe the lawyers will have their say.

In the meanwhile, we should leave it as is, yes?

**Comment by mattl** [comment]
It looks bad to have something All Rights Reserved.

**Comment by no-reply** [comment]
Agreed.

**Comment by no-reply** [comment]
I opened a thread on the project Basecamp to push the discussion forward. Hopefully this can be resolved in short order.

https://basecamp.com/1768384/projects/5077375/messages/45191432

**Comment by anarchivist** [comment]
See PR #8.
